name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /tmp
          if [ -d "hng13-stage0-devops" ]; then
            cd hng13-stage0-devops
            git pull origin main
          else
            git clone git@github.com:tulbadex/hng13-stage0-devops.git
            cd hng13-stage0-devops
          fi
          sudo cp /tmp/hng13-stage0-devops/index.html /var/www/html/index.html
          sudo chown www-data:www-data /var/www/html/index.html
          sudo chmod 644 /var/www/html/index.html
          sudo systemctl reload nginx
          echo "Deployment completed - $(date)"